package com.studybloom.app.utils

import com.studybloom.app.models.Flashcard
import com.studybloom.app.models.FlashcardSet
import com.studybloom.app.models.Quiz
import com.studybloom.app.models.QuizQuestion
import org.json.JSONArray
import org.json.JSONObject

/**
 * Helper class to parse structured JSON generated by Gemini AI
 * into strongly-typed Kotlin data classes (FlashcardSet and Quiz).
 * Uses standard Android org.json package to keep it beginner-friendly.
 */
object JsonParserHelper {

    /**
     * Cleans raw AI response text by stripping Markdown code blocks if present
     * (e.g. ```json ... ```).
     */
    fun cleanJsonResponse(rawText: String): String {
        var clean = rawText.trim()
        if (clean.startsWith("```json")) {
            clean = clean.removePrefix("```json")
        } else if (clean.startsWith("```")) {
            clean = clean.removePrefix("```")
        }
        if (clean.endsWith("```")) {
            clean = clean.removeSuffix("```")
        }
        return clean.trim()
    }

    /**
     * Parses JSON string into a FlashcardSet object.
     * Expected format:
     * {
     *   "title": "Topic Name",
     *   "cards": [
     *     { "question": "Question here", "answer": "Answer here" }
     *   ]
     * }
     */
    fun parseFlashcards(
        rawJson: String,
        userId: String,
        defaultTitle: String,
        subject: String
    ): FlashcardSet {
        val cleanJson = cleanJsonResponse(rawJson)
        val jsonObject = JSONObject(cleanJson)

        val title = jsonObject.optString("title", defaultTitle).ifBlank { defaultTitle }
        val cardsArray = jsonObject.optJSONArray("cards") ?: JSONArray()
        val cardsList = mutableListOf<Flashcard>()

        for (i in 0 until cardsArray.length()) {
            val cardObj = cardsArray.optJSONObject(i) ?: continue
            val q = cardObj.optString("question", "").trim()
            val a = cardObj.optString("answer", "").trim()
            if (q.isNotEmpty() && a.isNotEmpty()) {
                cardsList.add(Flashcard(question = q, answer = a))
            }
        }

        return FlashcardSet(
            id = "", // Will be assigned by Firestore or caller
            userId = userId,
            title = title,
            subject = subject,
            cards = cardsList,
            createdAt = System.currentTimeMillis()
        )
    }

    /**
     * Parses JSON string into a Quiz object.
     * Expected format:
     * {
     *   "title": "Topic Quiz",
     *   "questions": [
     *     {
     *       "question": "Question text",
     *       "options": ["A", "B", "C", "D"],
     *       "correctAnswer": 0
     *     }
     *   ]
     * }
     */
    fun parseQuiz(
        rawJson: String,
        userId: String,
        defaultTitle: String,
        subject: String
    ): Quiz {
        val cleanJson = cleanJsonResponse(rawJson)
        val jsonObject = JSONObject(cleanJson)

        val title = jsonObject.optString("title", defaultTitle).ifBlank { defaultTitle }
        val questionsArray = jsonObject.optJSONArray("questions") ?: JSONArray()
        val questionsList = mutableListOf<QuizQuestion>()

        for (i in 0 until questionsArray.length()) {
            val qObj = questionsArray.optJSONObject(i) ?: continue
            val qText = qObj.optString("question", "").trim()
            val optArray = qObj.optJSONArray("options") ?: JSONArray()
            val options = mutableListOf<String>()

            for (j in 0 until optArray.length()) {
                options.add(optArray.optString(j, "").trim())
            }

            var correctIdx = qObj.optInt("correctAnswer", 0)
            // Safety check for 1-based indexing if AI returns 1..4 instead of 0..3
            if (correctIdx >= options.size && options.isNotEmpty()) {
                correctIdx = (correctIdx - 1).coerceIn(0, options.size - 1)
            } else if (correctIdx < 0) {
                correctIdx = 0
            }

            if (qText.isNotEmpty() && options.isNotEmpty()) {
                questionsList.add(
                    QuizQuestion(
                        question = qText,
                        options = options,
                        correctAnswer = correctIdx
                    )
                )
            }
        }

        return Quiz(
            id = "", // Assigned by Firestore or caller
            userId = userId,
            title = title,
            subject = subject,
            questions = questionsList,
            createdAt = System.currentTimeMillis()
        )
    }
}
