package com.studybloom.app.activities

import android.content.Intent
import android.os.Bundle
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import com.google.android.material.card.MaterialCardView
import com.studybloom.app.R
import com.studybloom.app.databinding.ActivityQuizBinding
import com.studybloom.app.models.Quiz
import com.studybloom.app.models.QuizQuestion

/**
 * QuizActivity:
 * Presents multiple-choice questions generated by Gemini AI.
 * Demonstrates:
 * - Dynamic view state manipulation for option selection
 * - Score calculations and tracking
 * - Passing complex results to ResultActivity via Intent extras
 */
class QuizActivity : AppCompatActivity() {

    private lateinit var binding: ActivityQuizBinding

    private var quiz: Quiz? = null
    private var questions: List<QuizQuestion> = emptyList()
    private var currentQuestionIndex = 0

    private var selectedOptionIndex: Int = -1
    private var correctAnswersCount = 0
    private var incorrectAnswersCount = 0

    private lateinit var optionCards: List<MaterialCardView>

    companion object {
        const val EXTRA_QUIZ = "extra_quiz"
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityQuizBinding.inflate(layoutInflater)
        setContentView(binding.root)

        @Suppress("DEPRECATION")
        quiz = intent.getSerializableExtra(EXTRA_QUIZ) as? Quiz

        questions = quiz?.questions ?: emptyList()

        if (questions.isEmpty()) {
            Toast.makeText(this, "No quiz questions found!", Toast.LENGTH_SHORT).show()
            finish()
            return
        }

        optionCards = listOf(
            binding.cardOption0,
            binding.cardOption1,
            binding.cardOption2,
            binding.cardOption3
        )

        binding.tvQuizTitleHeader.text = quiz?.title ?: getString(R.string.quiz_title)
        binding.pbQuizProgress.max = questions.size

        setupListeners()
        displayQuestion(currentQuestionIndex)
    }

    private fun setupListeners() {
        binding.btnBackQuiz.setOnClickListener {
            finish()
        }

        // Click listeners for the 4 option cards
        optionCards.forEachIndexed { index, card ->
            card.setOnClickListener {
                selectOption(index)
            }
        }

        // Next or Finish Button
        binding.btnNextOrSubmitQuiz.setOnClickListener {
            handleNextOrSubmit()
        }
    }

    private fun displayQuestion(index: Int) {
        val q = questions[index]
        selectedOptionIndex = -1
        resetOptionCardStyles()

        binding.tvQuizQuestionCount.text = "Question ${index + 1} of ${questions.size}"
        binding.tvQuestionBadge.text = "QUESTION ${index + 1}"
        binding.tvQuestionText.text = q.question
        binding.pbQuizProgress.progress = index + 1

        val options = q.options
        binding.tvOptionText0.text = options.getOrElse(0) { "" }
        binding.tvOptionText1.text = options.getOrElse(1) { "" }
        binding.tvOptionText2.text = options.getOrElse(2) { "" }
        binding.tvOptionText3.text = options.getOrElse(3) { "" }

        // Update button text for last question
        if (index == questions.size - 1) {
            binding.btnNextOrSubmitQuiz.text = getString(R.string.btn_finish_quiz)
        } else {
            binding.btnNextOrSubmitQuiz.text = getString(R.string.btn_next_question)
        }
    }

    private fun selectOption(index: Int) {
        selectedOptionIndex = index
        resetOptionCardStyles()

        // Highlight selected option card
        val selectedCard = optionCards[index]
        selectedCard.strokeColor = ContextCompat.getColor(this, R.color.bloom_pink_primary)
        selectedCard.setCardBackgroundColor(ContextCompat.getColor(this, R.color.bloom_pink_light))
    }

    private fun resetOptionCardStyles() {
        optionCards.forEach { card ->
            card.strokeColor = ContextCompat.getColor(this, R.color.bloom_divider)
            card.setCardBackgroundColor(ContextCompat.getColor(this, R.color.bloom_surface))
        }
    }

    private fun handleNextOrSubmit() {
        if (selectedOptionIndex == -1) {
            Toast.makeText(this, getString(R.string.please_select_option), Toast.LENGTH_SHORT).show()
            return
        }

        val currentQuestion = questions[currentQuestionIndex]
        if (selectedOptionIndex == currentQuestion.correctAnswer) {
            correctAnswersCount++
        } else {
            incorrectAnswersCount++
        }

        if (currentQuestionIndex < questions.size - 1) {
            currentQuestionIndex++
            displayQuestion(currentQuestionIndex)
        } else {
            finishQuizAndShowResults()
        }
    }

    private fun finishQuizAndShowResults() {
        val total = questions.size
        val score = correctAnswersCount
        val percentage = if (total > 0) ((score.toDouble() / total) * 100).toInt() else 0

        val intent = Intent(this, ResultActivity::class.java).apply {
            putExtra(ResultActivity.EXTRA_QUIZ_TITLE, quiz?.title ?: "StudyBloom Quiz")
            putExtra(ResultActivity.EXTRA_QUIZ_ID, quiz?.id ?: "")
            putExtra(ResultActivity.EXTRA_SUBJECT, quiz?.subject ?: "General")
            putExtra(ResultActivity.EXTRA_SCORE, score)
            putExtra(ResultActivity.EXTRA_TOTAL, total)
            putExtra(ResultActivity.EXTRA_PERCENTAGE, percentage)
            putExtra(ResultActivity.EXTRA_CORRECT, correctAnswersCount)
            putExtra(ResultActivity.EXTRA_INCORRECT, incorrectAnswersCount)
            putExtra(ResultActivity.EXTRA_QUIZ_OBJECT, quiz)
        }
        startActivity(intent)
        finish()
    }
}
